services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run uvicorn src:create_app --factory --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/app/src
    container_name: GeoSpatialAPI
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/app

  db:
    image: postgis/postgis:15-3.4
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
